# Generated by Django 4.2.14 on 2024-07-14 13:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_number', models.IntegerField(unique=True, verbose_name='Номер когорты')),
            ],
            options={'verbose_name': 'Когорта', 'verbose_name_plural': 'Когорты',},
        ),
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_number', models.IntegerField(unique=True, verbose_name='Номер спринта')),
            ],
            options={'verbose_name': 'Спринт', 'verbose_name_plural': 'Спринты',},
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'stars',
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message='Количество звезд не может быть меньше 1'
                            ),
                            django.core.validators.MaxValueValidator(
                                5, message='Количество звезд не может быть больше 5'
                            ),
                        ],
                        verbose_name='Награда',
                    ),
                ),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                (
                    'cohort',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='cohort',
                        to='reviews.cohort',
                        verbose_name='Когорта',
                    ),
                ),
                (
                    'reviewer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviewer',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Ревьюер',
                    ),
                ),
                (
                    'sprint',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sprint',
                        to='reviews.sprint',
                        verbose_name='Спринт',
                    ),
                ),
                (
                    'student',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='student',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Студент',
                    ),
                ),
            ],
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews', 'ordering': ['-date_created'],},
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('cohort', 'sprint', 'student'), name='unique_review'),
        ),
    ]
